name: flutter_starter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  firebase_core: "^0.7.0"
  firebase_analytics: "^7.0.1"
  firebase_auth: "^0.20.1"
  cloud_firestore: "^0.16.0+1"

  youtube_player_iframe: ^1.2.0+2
  just_audio: ^0.6.15+1

  # google_sign_in:
  # apple_sign_in:
  get: ^3.17.1
  get_storage: ^1.3.2

  # flutter_platform_widgets:
  flutter_sheet_localization: ^1.0.0
  simple_gravatar:
  bordered_text: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_sheet_localization_generator: ^1.0.0
  build_runner: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/default.png
    - assets/images/defaultDark.png

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
